config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  get 'about', to: 'pages#about'
  get 'settings', to: 'pages#settings'
  get 'rules', to: 'pages#rules'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'
  get 'confidentialite', to: 'pages#confidentialite'
  get 'store_outcome', to: 'forecasts#store_outcome', defaults: {format: :json}
  get 'store_outcome_b2e', to: 'forecasts#store_outcome_b2e', defaults: {format: :json}
  get 'store_outcome_under', to: 'forecasts#store_outcome_under', defaults: {format: :json}
  get 'store_outcome_striker1', to: 'forecasts#store_outcome_striker1', defaults: {format: :json}
  get 'confirm_pending', to: 'forecasts#confirm_pending', defaults: {format: :json}
  get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-3.amazonaws.com/storpesitemap/sitemap.xml.gz")
  post "/friends/add" => "friends/add"
  post "/friends/reject" => "friends/reject"
  post "/friends/remove" => "friends/remove"
  get "/friends/search" => "friends/search"
  post "/friends/search" => "friends/search"

  resources :pages, only: [:show]
  resources :articles
  resources :matches, only: [:index] do
    resources :forecasts, only: [:new, :create, :show, :confirm_pending]
  end
  resources :forecasts, only: [:destroy]
  resources :seasons, only: [:show]
  resources :player_seasons
  resources :friends, only: [:index, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_friends.html.erb
<div class="position-relative">
  <div class="topimagechampionship w-100 d-flex mb-3">
    <h2 class="toptitle m-auto">MES AMIS</h2>
  </div>
  <div class="d-flex justify-content-center mt-2 mb-2">
    <div class="info  d-flex  flex-column">
      <div class=" d-flex justify-content-around mt-4" style=" padding: 0 20%;">
        <div class="up">
          <div class="params">
            <%= link_to contact_path do  %>
              <%= cl_image_tag "https://res.cloudinary.com/dhu7op4vc/image/upload/c_scale,w_32/v1601900588/PARAMETERS_mksd9n.png" %>
            <% end %>
          </div>
          <div class="blason">
            <% if  current_user.player_seasons[0].blason.present?%>
              <%= link_to edit_player_season_path(current_user.player_seasons[0].id) do %>
                <%= cl_image_tag current_user.player_seasons[0].blason.split('<img src="').join("").split('/>').join("").split('"').join("")%>
              <% end %>
            <% else %>
              <%= link_to edit_player_season_path(current_user.player_seasons[0].id) do %>
                <i class="fas fa-plus-circle" style="color: #FBB03B;"></i>
              <% end %>
            <% end %>
          </div>
          <h3 class="typo">Pseudo: <%= current_user.pseudo %></h3>
          <div class="btn-ranking d-flex justify-content-center">
            <h3 class="typoleague mt-2" data-toggle="modal" data-target="#champModal" type="button">Division: <%= current_user.player_seasons[0].championship.name %></h3>
          </div>
          <div class="modal fade" id="champModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Championnat</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="d-flex flex-column m-auto mt-4 text-white">
                    <p>Légende</p>
                    <p>Champion</p>
                    <p>Pro</p>
                    <p>Semi-Pro</p>
                    <p>Amateur</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <svg class=" center-block mx-auto mt-1" xmlns="https://www.w3.org/2000/svg" width="247.39" height="0.5" viewBox="0 0 247.39 0.5"><defs><style>.a{fill:none;stroke:#fff;stroke-miterlimit:10;stroke-width:0.5px;}</style></defs><line class="a" x1="247.39" transform="translate(0 0.25)"/></svg>
      <table class="table table-borderless mb-4">
        <thead>
          <tr>
            <th scope="col">PSEUDO</th>
            <th scope="col">CHAMPIONNAT</th>
            <th scope="col">PRONOS</th>
            <th scope="col">PTS</th>
          </tr>
        </thead>
        <% if current_user.friends == [] %>
          <tbody>
            <p class="typopo text-center">C'est le moment d'ajouter tes potes 🚀</p>
          </tbody>
        <% else %>
          <% @user.friends.each do |friend| %>
            <tbody>
              <tr>
                <td><%= friend.pseudo %></td>
                <td><%= friend.player_seasons[0].championship.name %></td>
                <td><%= friend.forecasts.where(season_id: Season.last.id).count %></td>
                <td><%= friend.player_seasons[0].number_of_points %></td>
              </tr>
            </tbody>
          <% end %>
        <% end %>
      </table>
      <div class="btn-ranking d-flex justify-content-center">
        <button data-toggle="modal" data-target="#exampleModal" type="button" class="btn btn-outline-light btnbis typo">Voir le classement</button>
      </div>
      <div class="d-flex justify-content-center">
        <%= link_to 'Ma carrière', player_season_path(current_user.id), class: "d-flex justify-content-center btn btn-success" %>
      </div>
      <div class="d-flex justify-content-center">
        <%= link_to 'La Gazette', articles_path, class: "d-flex justify-content-center btn btn-light mt-4" %>
      </div>
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header sticky pt-5">
              <h5 class="modal-title" id="exampleModalLabel">CLASSEMENT</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="d-flex flex-column m-auto mt-4">
                <table class="table table-borderless mb-4">
                  <thead>
                    <tr>
                      <th scope="col">POS</th>
                      <th scope="col">PSEUDO</th>
                      <th scope="col">CHAMPIONNAT</th>
                      <th scope="col">PRONOS</th>
                      <th scope="col">PTS</th>
                    </tr>
                  </thead>
                  <% classement = {} %>
                  <% x = 0 %>
                  <% @friends.each do |friend| %>
                    <% classement[friend] = friend.player_seasons[0].number_of_points %>
                  <% end %>
                  <tbody>
                    <tr>
                      <td class="cla">0</td>
                      <td class="cla"><%= current_user.pseudo %></td>
                      <td class="cla"><%= current_user.player_seasons[0].championship.name %></td>
                      <td class="cla"><%= current_user.player_seasons[0].forecasts.where(season_id: Season.last.id).count %></td>
                      <td class="cla"><%= current_user.player_seasons[0].number_of_points %></td>
                    </tr>
                    <% classement.to_a.sort_by{|k,v| v}.reverse.each do |player| %>
                      <tr>
                        <td scope="row"><%= x += 1 %></td>
                        <td><%= player[0].pseudo %></td>
                        <td><%= player[0].player_seasons[0].championship.name %></td>
                        <td><%= player[0].player_seasons[0].forecasts.where(season_id: Season.last.id).count %></td>
                        <td><%= player[0].player_seasons[0].number_of_points %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-2 mb-2">
  <div class="info  d-flex  flex-column">
    <header class="ui basic segment">
      <h3 class="typo text-center mt-2">Ajoutes tes amis 👇 (attention à l'ortographe)</h3>
    </header>
    <!-- Test 1 -->
      <!-- <div class="ui basic segment">
        <%#= form_tag ({controller: 'friends', action: 'search'}) do %>
          <div class="text-center mt-2">
            <input type="align-items-center mt-2" name="search" id="search">
          </div>
          <input class="btn btn-light mt-3" type="submit" name="commit" value="Chercher" data-disable-with="Search">
        <%# end %>
      </div> -->
      <!-- Test 2 -->
      <div class="container">
        <div class="row justify-content-center align-items-center">
          <div class="col-8" data-controller="search">
             <div class="form">
              <%= form_tag ({controller: 'friends', action: 'search'}) do %>
                <input class="form-control" id="search-input" name="search" type="text" placeholder='Son doux pseudo' data-algolia-id = "<%= ENV["ALGOLIASEARCH_APPLICATION_ID"] %>" data-algolia-search-key = "<%= ENV["ALGOLIASEARCH_API_KEY_SEARCH"] %>" data-search-target="searchBar"/>
                <input class="btn btn-light mt-3" type="submit" name="commit" value="Chercher" data-disable-with="Search">
              <% end %>
             </div>
          </div>
        </div>
      </div>
  </div>
</div>
 <div class="d-flex justify-content-center mt-2 mb-2">
  <div class="info  d-flex  flex-column">
    <div class=" d-flex justify-content-around mt-4" style=" padding: 0 20%;">
      <% if @user.friend_requests? %>
        <div class="d-flex justify-content-center mt-2 mb-2">
          <div class="info  d-flex  flex-column">
            <header class="ui basic segment">
              <h3 class="typo text-center mt-2">Requêtes d'amis:</h3>
            </header>
            <% @requests.each do |friend| %>
              <section class="ui basic segment">
                <span class="ui green header">
                  <p class="typopo"> Pseudo: <%= friend.pseudo%></p>
                  <p class="typopo"> Championnat: <%= friend.player_seasons[0].championship.name%></p>
                  <p class="typopo"> Nombre de points: <%= friend.player_seasons[0].number_of_points%></p>
                </span>
                <div class="ui basic segment">
                  <%= form_tag ({controller: 'friends', action: 'add', method: 'post', id: friend.id}) do %>
                    <input class="btn btn-light mt-2" type=submit value='Accepter'>
                  <% end %>
                  <%= form_tag ({controller: 'friends', action: 'reject', method: 'post', id: friend.id}) do %>
                    <input class="btn btn-danger text-center mt-3" type=submit value='Refuser'>
                  <% end %>
                </div>
              </section>
            <% end %>
      <% else %>
      <div class="d-flex justify-content-center mt-2 mb-2">
        <div class="info  d-flex  flex-column">
          <header class="ui basic segment">
            <h3 class="typo text-center mt-2">Requêtes d'amis:</h3>
          </header>
          <p class="typopo mt-4">Tu n'as pas encore reçu de demandes 🤷‍♂️</p>
        </div>
      </div>
      <% end %>
          </div>
        </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center mt-2 mb-2">
  <div class="info  d-flex  flex-column">
    <div class=" d-flex justify-content-around mt-4" style=" padding: 0 20%;">
      <% if @user.requested_friends? %>
        <div class="ui vertical segment">
            <header class="ui basic segment">
              <h3 class="typo text-center mt-2">Demandes en attentes:</h3>
            </header>
            <% @pending.each do |friend| %>
              <section class="ui basic segment">
                <span class="ui yellow header">
                  <p class="typoleague text-center"><%= friend.pseudo%> ne t'a pas encore accepté ...</p>
                </span>
              </section>
            <% end %>
        </div>
        <% else %>
        <header class="ui basic segment">
          <h3 class="typo text-center mt-2">Demandes en attentes:</h3>
          <p class="typopo mt-4">Ils ne t'ont pas encore répondu 🤷‍♂️</p>
        </header>
      <% end %>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center">
  <footer class="footer-match">
    <div class="footer-links" style="display: flex; align-items: center;">
      <a href="twitter://STORPE4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-twitter"></i></a>
      <a href="fb://group//1039435053063312" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-facebook-square"></i></a>
      <a href="instagram://storpe4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-instagram"></i></a>
    </div>
  </footer>
</div>

<%=  render "shared/navbarbottom" %>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5fa03faa8c2147b7"></script>

app/views/shared/_friendslosc.html.erb
<body style="background: #101050;">
  <div class="position-relative">
    <div class="topimagechampionshiplosc w-100 d-flex mb-3">
      <h2 class="toptitle m-auto">MES AMIS</h2>
    </div>
    <div class="d-flex justify-content-center mt-2 mb-2">
      <div class="infolosc  d-flex  flex-column">
        <div class=" d-flex justify-content-around mt-4" style=" padding: 0 20%;">
          <div class="up">
            <div class="params">
              <%= link_to contact_path do  %>
                <%= cl_image_tag "https://res.cloudinary.com/dhu7op4vc/image/upload/c_scale,w_32/v1601900588/PARAMETERS_mksd9n.png" %>
              <% end %>
            </div>
            <div class="blason">
              <% if  current_user.player_seasons[0].blason.present?%>
                <%= link_to edit_player_season_path(current_user.player_seasons[0].id) do %>
                  <%= cl_image_tag current_user.player_seasons[0].blason.split('<img src="').join("").split('/>').join("").split('"').join("")%>
                <% end %>
              <% else %>
                <%= link_to edit_player_season_path(current_user.player_seasons[0].id) do %>
                  <i class="fas fa-plus-circle" style="color: #E01E17;"></i>
                <% end %>
              <% end %>
            </div>
            <h3 class="typo">Pseudo: <%= current_user.pseudo %></h3>
            <div class="btn-ranking d-flex justify-content-center">
              <h3 class="typoleaguelosc mt-2" data-toggle="modal" data-target="#champModal" type="button">Division: <%= current_user.player_seasons[0].championship.name %></h3>
            </div>
            <div class="modal fade" id="champModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Championnat</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="d-flex flex-column m-auto mt-4 text-white">
                      <p>Légende</p>
                      <p>Champion</p>
                      <p>Pro</p>
                      <p>Semi-Pro</p>
                      <p>Amateur</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <svg class=" center-block mx-auto mt-1" xmlns="https://www.w3.org/2000/svg" width="247.39" height="0.5" viewBox="0 0 247.39 0.5"><defs><style>.a{fill:none;stroke:#fff;stroke-miterlimit:10;stroke-width:0.5px;}</style></defs><line class="a" x1="247.39" transform="translate(0 0.25)"/></svg>
        <table class="table table-borderless mb-4">
          <thead>
            <tr>
              <th scope="col">PSEUDO</th>
              <th scope="col">CHAMPIONNAT</th>
              <th scope="col">PRONOS</th>
              <th scope="col">PTS</th>
            </tr>
          </thead>
          <% if current_user.friends == [] %>
            <tbody>
              <p class="typopo text-center">C'est le moment d'ajouter tes potes 🚀</p>
            </tbody>
          <% else %>
            <% @user.friends.each do |friend| %>
              <tbody>
                <tr>
                  <td><%= friend.pseudo %></td>
                  <td><%= friend.player_seasons[0].championship.name %></td>
                  <td><%= friend.forecasts.where(season_id: Season.last.id).count %></td>
                  <td><%= friend.player_seasons[0].number_of_points %></td>
                </tr>
              </tbody>
            <% end %>
          <% end %>
        </table>
        <div class="btn-ranking d-flex justify-content-center">
          <button data-toggle="modal" data-target="#exampleModal" type="button" class="btn btn-outline-lightlosc btnbis typo">Voir le classement</button>
        </div>
        <div class="d-flex justify-content-center">
          <%= link_to 'Ma carrière', player_season_path(current_user.id), class: "d-flex justify-content-center btn btn-success" %>
        </div>
        <div class="d-flex justify-content-center">
          <%= link_to 'La Gazette', articles_path, class: "d-flex justify-content-center btn btn-light mt-4" %>
        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header sticky pt-5">
                <h5 class="modal-title" id="exampleModalLabel">CLASSEMENT</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div class="d-flex flex-column m-auto mt-4">
                  <table class="table table-borderless mb-4">
                    <thead>
                      <tr>
                        <th scope="col">POS</th>
                        <th scope="col">PSEUDO</th>
                        <th scope="col">CHAMPIONNAT</th>
                        <th scope="col">PRONOS</th>
                        <th scope="col">PTS</th>
                      </tr>
                    </thead>
                    <% classement = {} %>
                    <% x = 0 %>
                    <% @friends.each do |friend| %>
                      <% classement[friend] = friend.player_seasons[0].number_of_points %>
                    <% end %>
                    <tbody>
                      <tr>
                        <td class="cla">0</td>
                        <td class="cla"><%= current_user.pseudo %></td>
                        <td class="cla"><%= current_user.player_seasons[0].championship.name %></td>
                        <td class="cla"><%= current_user.player_seasons[0].forecasts.where(season_id: Season.last.id).count %></td>
                        <td class="cla"><%= current_user.player_seasons[0].number_of_points %></td>
                      </tr>
                      <% classement.to_a.sort_by{|k,v| v}.reverse.each do |player| %>
                        <tr>
                          <td scope="row"><%= x += 1 %></td>
                          <td><%= player[0].pseudo %></td>
                          <td><%= player[0].player_seasons[0].championship.name %></td>
                          <td><%= player[0].player_seasons[0].forecasts.where(season_id: Season.last.id).count %></td>
                          <td><%= player[0].player_seasons[0].number_of_points %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center mt-2 mb-2">
    <div class="infolosc  d-flex  flex-column">
      <header class="ui basic segment">
        <h3 class="typo text-center mt-2">Ajoutes tes amis 👇 (attention à l'ortographe)</h3>
      </header>
      <!-- Test 1 -->
        <!-- <div class="ui basic segment">
          <%#= form_tag ({controller: 'friends', action: 'search'}) do %>
            <div class="text-center mt-2">
              <input type="align-items-center mt-2" name="search" id="search">
            </div>
            <input class="btn btn-light mt-3" type="submit" name="commit" value="Chercher" data-disable-with="Search">
          <%# end %>
        </div> -->
        <!-- Test 2 -->
        <div class="container">
          <div class="row justify-content-center align-items-center">
            <div class="col-8" data-controller="search">
               <div class="form">
                <%= form_tag ({controller: 'friends', action: 'search'}) do %>
                  <input class="form-control" id="search-input" name="search" type="text" placeholder='Son doux pseudo' data-algolia-id = "<%= ENV["ALGOLIASEARCH_APPLICATION_ID"] %>" data-algolia-search-key = "<%= ENV["ALGOLIASEARCH_API_KEY_SEARCH"] %>" data-search-target="searchBar"/>
                  <input class="btn btn-light mt-3" type="submit" name="commit" value="Chercher" data-disable-with="Search">
                <% end %>
               </div>
            </div>
          </div>
        </div>
    </div>
  </div>
   <div class="d-flex justify-content-center mt-2 mb-2">
    <div class="infolosc  d-flex  flex-column">
      <div class=" d-flex justify-content-around mt-4" style=" padding: 0 20%;">
        <% if @user.friend_requests? %>
          <div class="d-flex justify-content-center mt-2 mb-2">
            <div class="infolosc  d-flex  flex-column">
              <header class="ui basic segment">
                <h3 class="typo text-center mt-2">Requêtes d'amis:</h3>
              </header>
              <% @requests.each do |friend| %>
                <section class="ui basic segment">
                  <span class="ui green header">
                    <p class="typopo"> Pseudo: <%= friend.pseudo%></p>
                    <p class="typopo"> Championnat: <%= friend.player_seasons[0].championship.name%></p>
                    <p class="typopo"> Nombre de points: <%= friend.player_seasons[0].number_of_points%></p>
                  </span>
                  <div class="ui basic segment">
                    <%= form_tag ({controller: 'friends', action: 'add', method: 'post', id: friend.id}) do %>
                      <input class="btn btn-light mt-2" type=submit value='Accepter'>
                    <% end %>
                    <%= form_tag ({controller: 'friends', action: 'reject', method: 'post', id: friend.id}) do %>
                      <input class="btn btn-danger text-center mt-3" type=submit value='Refuser'>
                    <% end %>
                  </div>
                </section>
              <% end %>
        <% else %>
        <div class="d-flex justify-content-center mt-2 mb-2">
          <div class="infolosc  d-flex  flex-column">
            <header class="ui basic segment">
              <h3 class="typo text-center mt-2">Requêtes d'amis:</h3>
            </header>
            <p class="typopo mt-4">Tu n'as pas encore reçu de demandes 🤷‍♂️</p>
          </div>
        </div>
        <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-2 mb-2">
    <div class="infolosc  d-flex  flex-column">
      <div class=" d-flex justify-content-around mt-4" style=" padding: 0 20%;">
        <% if @user.requested_friends? %>
          <div class="ui vertical segment">
              <header class="ui basic segment">
                <h3 class="typo text-center mt-2">Demandes en attentes:</h3>
              </header>
              <% @pending.each do |friend| %>
                <section class="ui basic segment">
                  <span class="ui yellow header">
                    <p class="typoleaguelosc text-center"><%= friend.pseudo%> ne t'a pas encore accepté ...</p>
                  </span>
                </section>
              <% end %>
          </div>
          <% else %>
          <header class="ui basic segment">
            <h3 class="typo text-center mt-2">Demandes en attentes:</h3>
            <p class="typopo mt-4">Ils ne t'ont pas encore répondu 🤷‍♂️</p>
          </header>
        <% end %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <footer class="footer-match">
      <div class="footer-links" style="display: flex; align-items: center;">
        <a href="twitter://STORPE4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-twitter"></i></a>
        <a href="fb://group//1039435053063312" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-facebook-square"></i></a>
        <a href="instagram://storpe4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-instagram"></i></a>
      </div>
    </footer>
  </div>
</div>
<%=  render "shared/navbarbottomlosc" %>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5fa03faa8c2147b7"></script>

app/views/shared/_modal.html.erb
<!-- <div class="modal fade" id="exampleModal" tabindex="1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="false"> -->
  <!-- <div class="modal-dialog" role="document"> -->
    <div class="modal-content">
      <div class="float-right p-1">
      </div>
      <div class="modal-header">
        <h2 class="stat m-auto">Tu as réalisé tes 40 pronos !</h2>

      </div>
     <!--  <div class="modal-body pb-1" style="z-index: 100;">
        <p class="typopo mb-0">Retrouve les sur la page championnat !</p>
      </div> -->
      <div class="modal-footer d-flex justify-content-center">
        <button type="button" class="rejoins typopo"><%= link_to 'Checker mes pronos', season_path(current_user)%></button>
      </div>
    </div>
  <!-- </div> -->
<!-- </div> -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>