config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  get 'about', to: 'pages#about'
  get 'settings', to: 'pages#settings'
  get 'rules', to: 'pages#rules'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'
  get 'confidentialite', to: 'pages#confidentialite'
  get 'store_outcome', to: 'forecasts#store_outcome', defaults: {format: :json}
  get 'store_outcome_b2e', to: 'forecasts#store_outcome_b2e', defaults: {format: :json}
  get 'store_outcome_under', to: 'forecasts#store_outcome_under', defaults: {format: :json}
  get 'store_outcome_striker1', to: 'forecasts#store_outcome_striker1', defaults: {format: :json}
  get 'confirm_pending', to: 'forecasts#confirm_pending', defaults: {format: :json}
  get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-3.amazonaws.com/storpesitemap/sitemap.xml.gz")
  post "/friends/add" => "friends/add"
  post "/friends/reject" => "friends/reject"
  post "/friends/remove" => "friends/remove"
  get "/friends/search" => "friends/search"
  post "/friends/search" => "friends/search"

  resources :pages, only: [:show]
  resources :articles
  resources :matches, only: [:index] do
    resources :forecasts, only: [:new, :create, :show, :confirm_pending]
  end
  resources :forecasts, only: [:destroy]
  resources :seasons, only: [:show]
  resources :player_seasons
  resources :friends, only: [:index, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<h1>Introducing the company</h1>

<h3>Lorem ipsum dolor sit amet,
consectetur adipisicing elit.
Nulla, quia quis blanditiis saepe nam
aliquid quidem enim assumenda, qui, quas
iure temporibus.
Fugiat temporibus aut explicabo,
sequi maiores doloremque vitae.</h3>


<%= link_to "back to Home", root_path %>

app/views/pages/confidentialite.erb
<div class="position-relative">
<a href="https://www.iubenda.com/privacy-policy/16976895" class="iubenda-white iubenda-embed" title="Privacy Policy ">Politique de confidentialité</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
</div>

app/views/pages/contact.html.erb
<div class="position-relative">
  <div class="d-flex justify-content-center pt-5 mb-3">
    <%= cl_image_tag "https://res.cloudinary.com/dhu7op4vc/image/upload/v1598518816/Group_135_2x_eoeq1f.png", width: "290px"; %>
  </div>
  <div class="main">
    <div class="contact mt-5 mb-3">
      <p style="text-align: center;">Une suggestion ?</p>
      <a class="typeform-share button mt-4" href="https://form.typeform.com/to/vJ9bp59Y" data-mode="drawer_right" style="display:inline-block;text-decoration:none;background-color:white;color:#FBB03B;cursor:pointer;font-family:Helvetica,Arial,sans-serif;font-size:20px;line-height:50px;text-align:center;margin:0;height:50px;padding:0px 33px;border-radius:25px;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:bold;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;" target="_blank">Contacte-nous 📩</a> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm_share", b="https://embed.typeform.com/"; if(!gi.call(d,id)){ js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>
    </div>
  </div>
  <div class="test">
    <!-- <div class="main">
      <div class="contact mt-5 mb-3">
        <%= link_to "Mes paramètres", edit_player_season_path(current_user.player_seasons[0].id), :class => "btn-login" %>
      </div>
    </div> -->
    <div class="main">
      <div class="contact mt-5 mb-3">
        <%= link_to "Les règles du jeu", rules_path, :class => "btn-login" %>
      </div>
    </div>
  </div>
  <div class="main">

    <div class="contact mt-4 mb-2">
      <%= link_to "Se déconnecter", destroy_user_session_path, :class => "btn btn-signup mt-4", method: :delete %>
    </div>
  </div>

  <footer class="footer-contact">
    <div class="footer-icones" style="display: flex; align-items: center; font-size: 30px; margin-top: 20px;">
      <a href="twitter://STORPE4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-twitter"></i></a>
      <a href="fb://group//1039435053063312" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-facebook-square"></i></a>
      <a href="instagram://storpe4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-instagram"></i></a>
    </div>
    <!-- Load Facebook SDK for JavaScript -->
      <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            xfbml            : true,
            version          : 'v9.0'
          });
        };

        (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/fr_FR/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>

      <!-- Your Chat Plugin code -->
      <div class="fb-customerchat"
        attribution=setup_tool
        page_id="100665954734426"
        theme_color="#FBB03B"
        logged_in_greeting="Salut ! Comment puis-je t'aider ? "
        logged_out_greeting="Salut ! Comment puis-je t'aider ? ">
      </div>

  </footer>


  <%= render "shared/navbarbottom" %>
  <p style="color: white; text-align: center;">Politique de Confidentialité <a href="/confidentialite" style="color: #FBB03B">ici</a></p> .
  <script type='text/javascript'>
  (function()
  {
    if( window.localStorage )
    {
      if( !localStorage.getItem('firstLoad') )
      {
        localStorage['firstLoad'] = true;
        window.location.reload();
      }
      else
        localStorage.removeItem('firstLoad');
    }
  })();
</script>

</div>

app/views/pages/dashboard.html.erb
<% if current_user.club == nil %>
  <%= render "shared/dashboard" %>
<% else %>
  <%= render "shared/dashboardlosc" %>
<% end %>

app/views/pages/home.html.erb
<div class="position">
  <div class="content">
    <div class="main-image">
      <%= cl_image_tag "https://res.cloudinary.com/dhu7op4vc/image/upload/v1601458862/testlandingstrong-ombre_qfovua.png", :width=>"100%", :alt=>"Bannière STORPE" %>
    </div>
    <hr class="new2">
    <div class="desktop">
      <%= render "shared/desktop" %>
      <!-- Load Facebook SDK for JavaScript -->
      <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            xfbml            : true,
            version          : 'v9.0'
          });
        };

        (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/fr_FR/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>

      <!-- Your Chat Plugin code -->
      <div class="fb-customerchat"
        attribution=setup_tool
        page_id="100665954734426"
        theme_color="#FBB03B"
        logged_in_greeting="Salut ! Comment puis-je t'aider ? "
        logged_out_greeting="Salut ! Comment puis-je t'aider ? ">
      </div>
      <%= render "shared/footer" %>
    </div>
    <div class="phone">
      <%= render "shared/phone" %>
      <footer class="footer-match">
        <div class="foot-phrase">
          <p>Le sport c'est ici aussi 👉</p>
        </div>
        <div class="footer-links" style="display: flex; align-items: center;">
          <a href="twitter://STORPE4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-twitter"></i></a>
          <a href="fb://group//?id=%@storpe" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-facebook-square"></i></a>
          <a href="instagram://user?username=storpe4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-instagram"></i></a>
        </div>
      </footer>
    </div>
  </div>
<%= render "shared/new" %>
</div>

app/views/pages/rules.html.erb
<h1 class="title">Les règles du jeu</h1>

<div class="container">
  <h2>Qu'est ce que tu peux gagner ? 🤔</h2>
  <p>En fonction de ton niveau tu remportes des chèques cadeaux plus ou moins conséquents.</p>
  <ol>
    <li>Tu es vainqueur de la Division Champion tu remportes un chèque cadeau de <%= cl_image_tag "https://res.cloudinary.com/dhu7op4vc/image/upload/v1614611764/gold_fjeziz.png", width: "40px", height: "40px"  %> </li>
    <li>Tu es vainqueur de la Division Pro tu remportes chèque cadeau de<%= cl_image_tag "https://res.cloudinary.com/dhu7op4vc/image/upload/v1614612133/silver_gvr8zu.png", width: "40px", height: "40px"  %> </li>
    <li>Tu es vainqueur de la Division Semi-Pro tu remportes chèque cadeau de<%= cl_image_tag "https://res.cloudinary.com/dhu7op4vc/image/upload/v1614612132/bronze_rldcii.png", width: "40px", height: "40px"  %></ </li>
    <li>Tu es vainqueur de la Division Amateur tu remportes chèque cadeau de<%= cl_image_tag "https://res.cloudinary.com/dhu7op4vc/image/upload/v1614612132/fourth_jmdjjd.png", width: "40px", height: "40px"  %></li>
  </ol>

</div>

<div class="container">
  <ol>
    <li>Ton <span style="font-weight: bold;">Championnat</span> se déroule chaque semaine du <span style="color:#FBB03B;">Lundi au Dimanche, tu es au maximum 20 joueurs par division</span>.</li>
    <li>Pour lancer ta participation au Championnat, il te suffit de placer un premier <span style="font-weight: bold;">pronostic</span>.</li>
    <li>Tu peux ne pas jouer une semaine. Pour ne pas être pris en compte, tu dois faire 0 <span style="font-weight: bold;">pronostic</span>.</li>
    <li>Pour cela, rends-toi sur la page des <u><%= link_to "Matchs", matches_path%></u>. Pronostique un ou plusieurs matchs et assure-toi de les <span style="color:#FBB03B;">valider dans ton panier</span>. </li>
    <li>Chaque Championnat te permet de pronostiquer jusqu’à <span style="color:red;">40 rencontres sportives !</span></li>
    <li>Au cours de la semaine de jeu, rends-toi sur la page <u><%= link_to "Championnat", season_path(current_user.id)%></u> afin de garder un œil sur tes performances. Tu pourras visualiser ton classement et t’assurer que tes adversaires ne te devancent pas. </li>
    <li>En fin de Championnat, ton <span style="color:#FBB03B;">classement</span> final te permet d’évoluer de Division :</li>
      <ol>- Les 8 premiers du Championnat Amateur sont promus en Division Semi-Pro.</ol>
      <ol>- Les 6 premiers du Championnat Semi-Pro sont promus en Division Pro.</ol>
      <ol>- Les 4 premiers du Championnat Pro sont promus en Division Champion.</ol>
      <ol>- Les 4 derniers sont relégués en Division inférieure.</ol>
      <ol>- Le reste des joueurs sont maintenus dans cette même Division.</ol>
    <li>Le niveau des <span style="font-weight: bold;">championnats</span> est le suivant (du plus bas au plus haut): <span style="color:#FBB03B;">Amateur - Semi-Pro - Pro - Champion - Légende</span> (oui tu as encore un peu de chemin).</li>
    <li>Tu ne peux pas <span style="font-weight: bold;">jouer</span> cette semaine ? Ne t’inquiète pas. Si tu ne <span style="font-weight: bold;">pronostiques</span> aucun match, tu n’es pas pris en compte dans le Championnat en cours. Tu gardes donc ta place dans la <span style="font-weight: bold;">Division</span> dans laquelle tu te trouves.</li>
    <li>Tout au long de ta <span style="font-weight: bold;">carrière</span>, il te suffira de te rendre sur ton <u><%= link_to "Profil", player_season_path(current_user.id) %></u> afin d’avoir accès à l’ensemble de tes <span style="color:#FBB03B;">performances</span> depuis ton inscription.</li>
    <li>Chez <span style="font-weight: bold;">STORPE</span> les points sont pondérés. En effet les points que tu remportes prennent en compte la difficulté du pronostic que tu engages. Plus le <span style="font-weight: bold;">pronostic</span> est "simple" moins tu remportes de points et inversement.</li>
    <li>Tu peux également perdre des points en cas de pronostic incorrect. Ceci permet de créer des <span style="font-weight: bold;">classements</span> cohérents, qui prennent en compte tous les pronostics.</li>
    <li>Les points des rencontres que tu as pronostiqué sont crédités à 23h00, la surprise peut être bonne ou ... mauvaise.</li>
    <li>Les matchs sont publiés régulièrement à partir du Lundi à 16h00.</li>
    <li>Le Lundi c'est le grand jour ! Le classement définitif est à jour, à 15h00 c'est la relégation ou la promotion qui t'attend.</li>
  </ol>
</div>

<div class="container">
  <h2>À venir</h2>
  <p>Pronostiquer est avant tout un plaisir et un <span style="font-weight:bold; text-decoration: underline;">jeu</span>.</p>
  <ol>
    <li>Bientôt, tu auras la possibilité de remporter des <span style="color:#FBB03B;">Tokens</span> de jeu à la suite de ton Championnat. Cette monnaie virtuelle te permettra d’effectuer des achats dans la Boutique <span style="font-weight: bold;">STORPE</span> !</li>
    <li>En échangeant tes Tokens dans la Boutique, tu pourras obtenir des <span style="color:#FBB03B;">boosts de performance</span> ! Ces jokers te permettront d’accélérer ton ascension vers la plus <span style="font-weight: bold;">haute Division</span> !</li>
    <li>Tu aimerais prouver à tes amis que tu es <span style="color:#FBB03B;">meilleur</span> qu’eux ? Tu pourras bientôt les ajouter dans ta <span style="color:#FBB03B;">liste d’amis</span> afin qu’ils puissent suivre tes performances, et qui sait, un jour les retrouver dans ton <span style="color:#FBB03B;">Championnat</span> !</li>
    <li>Enfin nous allons ajouter de nouvelles <span style="font-weight:bold;">divisions de niveaux</span> au fur et à mesure que la <span style="color:#FBB03B;">communauté grossit</span>. </li>
  </ol>

</div>

<div class="main">
  <a class="typeform-share button mt-4" href="https://form.typeform.com/to/vJ9bp59Y" data-mode="drawer_right" style="display:inline-block;text-decoration:none;background-color:#FBB03B;color:white;cursor:pointer;font-family:Helvetica,Arial,sans-serif;font-size:20px;line-height:50px;text-align:center;margin:0;height:50px;padding:0px 33px;border-radius:25px;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:bold;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;" target="_blank">Contacte-nous 📩</a> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm_share", b="https://embed.typeform.com/"; if(!gi.call(d,id)){ js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>
</div>
<p style="text-align: center; color: #FBB03B; font-size: 20px; margin-bottom: 0; margin-top: 3px;">- ou -</p>
<footer class="footer-contact">
  <div class="foot-phrase" style="color: white; font-size: 20px;">
    <p>Échange avec nous 👉</p>
  </div>
  <div class="footer-icones" style="display: flex; align-items: center; font-size: 30px; margin-bottom: 75px;">
    <a href="twitter://STORPE4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-twitter"></i></a>
    <a href="fb://group//1039435053063312" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-facebook-square"></i></a>
    <a href="instagram://storpe4" style="text-decoration: none; padding: 0px 10px;"><i class="fab fa-instagram"></i></a>
  </div>
</footer>


<%= render "shared/navbarbottom" %>
<script type='text/javascript'>
  (function()
  {
    if( window.localStorage )
    {
      if( !localStorage.getItem('firstLoad') )
      {
        localStorage['firstLoad'] = true;
        window.location.reload();
      }
      else
        localStorage.removeItem('firstLoad');
    }
  })();
</script>